# === SAFFRON UNIFIED ENGINE CONFIGURATION ===

# === CORE ENGINE BEHAVIOR ===
active_model: auto
enable_auto_switch: true
fallback_model: starcoder2

# === ROUTING ENDPOINTS ===
routes:
  mistral: "/mistral"
  starcoder2: "/starcoder2"

# === MODEL ROUTING RULES ===
model_router:
  auto_routing_enabled: true
  prompt_classifier:
    enabled: true
    rules:
      - solidity|vyper|contract: use_starcoder2
      - zk|circom|cairo|proof: use_starcoder2
      - backend|infra|api|node|gossip|bft: use_mistral
      - trading|strategy|prediction|market: use_mistral
      - frontend|ui|react|html|tailwind: use_starcoder2
      - mobile|flutter|android|ios|react_native: use_starcoder2
      - exploit|malware|redteam|threat: use_mistral
  fallback_model: mistral
  manual_override: true

# === SUPPORTED LANGUAGES ===
code_domains:
  languages_supported:
    - python
    - go
    - rust
    - bash
    - solidity
    - vyper
    - cairo
    - circom
    - teal
    - move
    - wasm
    - javascript
    - typescript
    - html
    - css
    - json
    - yaml
    - dockerfile
    - sql
    - c
    - c++
    - dart
    - kotlin
    - swift

# === SUPPORTED BLOCKCHAIN PROTOCOLS ===
blockchain_protocols:
  evm_compatible:
    - ethereum
    - polygon
    - arbitrum
    - optimism
    - bnb_chain
    - avalanche
    - base
  non_evm:
    - bitcoin
    - tron
    - solana
    - cosmos
    - polkadot
    - sui
    - aptos
    - near
    - algorand
  stablecoin_aware:
    - usdt
    - usdc
    - dai
    - tusd
    - busd
    - frax
  defi_protocols:
    - uniswap
    - curve
    - aave
    - compound
    - yearn
    - balancer
    - 1inch
    - sushi
    - pancake
    - synthetix
  zk_protocols:
    - zksync
    - starknet
    - polygon_zkevm
    - scroll
    - halo2
    - aztec
    - mina

# === UI/UX & DESIGN SUPPORT ===
ui_support:
  design_languages:
    - react
    - tailwind
    - nextjs
    - vue
    - flutter
    - react_native
    - native_ios
    - native_android
  adaptive_ui_learning:
    enabled: true
    source_libraries:
      - dribbble_ui_trends
      - github_ui_templates
      - open_source_component_libraries
      - figma_tokens

# === MONITORING & ALERTING ===
monitoring:
  enable_logs: true
  show_gpu_usage: true
  show_ram_usage: true
  disk_alert_threshold: 90
  auto_alerts: true
  notify_user_on_failures: true

# === SELF-LEARNING ENGINE ===
learning_sources:
  enable_online_learning: true
  allow_ui_source_addition: true
  sources:
    - github_copilot
    - huggingface_datasets
    - claude_behaviors
    - gpt_sample_chats
    - codeforces
    - leetcode
    - kaggle
    - ai_papers_summary
    - zkp_repos
    - github_exploitdb
    - public_chain_datasets
    - react_ui_snippets
    - flutter_components
  auto_index_sources: true

# === SECURITY STACK ===
security_stack:
  encryption_protocols:
    - AES-256
    - RSA-2048/4096
    - ECDSA
    - Curve25519
    - ChaCha20
  secure_hashes:
    - SHA-256
    - BLAKE2
    - Keccak256
    - Argon2
  transport_security:
    ssl_tls_versions:
      - TLS 1.2
      - TLS 1.3
    allow_https_enforcement: true
    enable_cert_check: true
    reverse_proxy_aware: true
  authentication_aware:
    - JWT
    - OAuth2
    - API Key Rotation
    - MultiSig Logic
    - biometric_token_compatibility: true

# === BACKEND SERVER TECH AWARENESS ===
backend_stack_support:
  supported_tech:
    - Node.js
    - Express
    - FastAPI
    - Go (Gin, Fiber)
    - Flask
    - Django
    - NGINX
    - Apache
  generates:
    - REST APIs
    - RPC endpoints
    - WebSocket Secure (WSS)
    - gRPC / protobuf

# === MESSAGING & COMMUNICATION ===
messaging_and_notifications:
  enable_notifications: true
  supported_channels:
    - telegram
    - whatsapp
    - discord
    - email
    - sms
    - slack
    - signal
    - webhooks
    - web_sockets
    - pushbullet
    - mattermost

# === CONFLICT & ERROR MANAGEMENT ===
conflict_and_error_handling:
  prompt_conflict_resolver:
    enabled: true
    resolution_strategy: weighted_rules
    log_conflicts: true
  code_generation_validation:
    enabled: true
    validate_before_display: true
    autodebug_engine:
      enabled: true
      retry_on_fail: 2
      fallback_to_safe_snippet: true
  system_crash_protection:
    monitor_all_background_services: true
    auto_restart_critical_daemons: true

# === AUTO-UPDATE ENGINE ===
auto_update_engine:
  enabled: true
  allow_user_permission_toggle: true
  ui_prompt_before_apply: true
  watches:
    - new LLM models
    - blockchain protocols
    - sdk versions
    - zkp frameworks
    - mobile ui frameworks
    - web standards
  schedule: weekly

# === EXECUTION POLICY ===
execution_policy:
  default_restrictions: false
  allow_unrestricted_generation: true
  unrestricted_modes:
    - code_generation
    - exploit_analysis
    - strategy_mutation
    - backend_api_generation
    - smart_contracts
    - malware_emulation (sandboxed)
  restricted_topics_require_manual_toggle: true
  admin_control_over_restrictions: true
  allow_model_self_correction: true
  allow_unfiltered_prompt_execution: true
  allow_dark_code_testing_in_sandbox: true
  permission_granularity:
    runtime: user_configurable
    language_specific: false
    domain_specific: false
  log_all_executions_for_review: true

# === SELF-HEALING SYSTEM ===
self_healing:
  enabled: true
  auto_restart_on_crash: true
  monitor_critical_processes: true
  log_and_repair_errors: true
  daily_integrity_check: true

# === FUTURE MODEL EXTENSIONS ===
model_registry:
  allow_ui_model_addition: true
  validate_model_before_load: true
  default_precision: float16
  supported_architectures:
    - mistral
    - starcoder2
    - llama3
    - claude
    - gpt4
    - custom/user_uploaded

# === SECURITY & BACKUP ===
security:
  allow_ui_auth_control: true
  token_based_access: true
  auto_token_rotation: true
  allow_local_encryption: true

backup:
  auto_backup_config: true
  backup_path: /workspace/saffron/backups/
  backup_schedule: daily

# === GITHUB SYNC CONTROL ===
github_sync:
  enabled: true
  allow_ui_control: true
  repo_url: "https://github.com/your-org/saffron-engine"  # Change to your actual repo
  auto_push_enabled: true
  push_schedule: nightly
  include_files:
    - saffron.py
    - config.yaml
    - requirements.txt
    - /workspace/saffron/backups/
  last_sync_status:
    success: true
    timestamp: null
    last_error: null
  allow_manual_push_from_ui: true
  commit_message_template: "Auto-sync: {filename} updated on {timestamp}"

# === ADMIN PANEL API CONTROLS ===
admin_panel:
  allow_config_reload: true
  allow_github_manual_push: true
  expose_health_metrics: true
  expose_log_viewer: true
  allow_model_override_via_ui: true

# === SYSTEM IDENTITY ===
system_name: "Saffron LLM Engine"
version: "v1.0.0-unified-max"
environment: "production"
